name: Docker images
on:
  push: 
   branches: 
    - masterru

jobs:
  build:
   runs-on : ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v3
      with:
       username: ${{secrets.DOCKER_USERNAME}}
       password: ${{secrets.DOCKER_PASSWORD}}
    - name: build and push
      uses: docker/build-push-action@v3
      with:
       push: true
       tag: anilkumar1146/workflow:latest
    
