name: Hello World
on: 
 push:
  branches:
   - master
   
jobs:
 build:
  runs-on: self-hosted
  steps:
     - name: Code checkout
       uses: actions/checkout@v3
     - name: Step up Java 
       uses: actions/setup-java@v4
       with:
        distribution: 'temurin'
        java-version: '17'
     - name: Install Java Dependices
       run: sudo apt install maven -y
     - name: build binary code
       run: mvn clean install
