name: Hello World
on:  
 push:
  branches: 
   - master
   
jobs:
 build:
  runs-on: self-hosted
  steps:
     - name: Code checkout
       uses: actions/checkout@v3
     - name: Step up Java 
       uses: actions/setup-java@v4
       with:
        distribution: 'temurin'
        java-version: '17'
     - name: Configure the Aws-cli
       uses: aws-actions/configure-aws-credentails@v3
       with: 
        access_key_id: ${{ secrets.KEY_ID }}
        access_secret_token: ${{ secrets.TOEKN }}
        access_region: 'ap-south-1'
     - name: Login to aws registry  
       uses: aws-actions/amazon-aws-login@v4
     - name: Install Java Dependices
       run: sudo apt update && sudo apt install maven -y
     - name: build binary code
       run: mvn clean install
     - name: Docker build and push
       uses: docker/build-push-actions@v3
       with:
        context: .
        push: true
        file: ./Dockerfile
        tag: githubaction:latest public.ecr.aws/j8p4c8m8/githubaction:1.0
