name: Hello World
on: 
 push:
  branches:
   - master
   
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
     - name: Code checkout
       uses: actions/checkout@v3
     - name: Step up Java 
       uses: actions/set-up-java@v3
       with:
        java-version: '17'
        cache: maven     
