name: Hello World
on: 
 push:
  branches:
   - master
   
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
     - name: Code checkout
       uses: actions/checkout@v3
     - name: Step up Java 
       uses: actions/setup-java@v4
       with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven     
     - name: build binary code
       run: mvn clean install
