name: Hello World
on: 
 push:
  branches:
   -main
   
jobs:
 build:
  runs-on: self-hosted
  steps:
     - name: Code checkout
       uses: actions/checkout@v3
     - name: Step up Java 
       uses: actions/set-up-java@v3
       with:
        java-version: '17'
     - name: Install Dependeines
       run: sudo apt install maven -y  
