name: Hello-world
on: 
   push:
        branches:
                 - master

jobs:
  firs-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Print message
        run: echo "Hello wordls tested"
       
  run-python:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: Install python
          uses: actions/setup-python@v3
          with: 
            python-version: 3.9
        - name: python dependenceies
          run: |
            python -m pip install  --upgrade pip
            pip install pytest
        - name: Run testcase
          run: pytest math.py
           
           

    
